baseURL=https://ws0.techstartacademy.io/stage-march.admin.html
chromedriverpath=/Users/svitlanashnipova/IdeaProjects/Framework/Drivers/chromedriver_copy
safaridriverpath= /urs/bin/safaridriver
JSONFilePAth =/Users/svitlanashnipova/IdeaProjects/framework-testsCPB/Framework/JSONFile/upload_test.json
imageFilePath = /Users/svitlanashnipova/IdeaProjects/framework-testsCPB/Framework/JSONFile/case.jpg
imageFoxFilepath=/Users/svitlanashnipova/IdeaProjects/framework-testsCPB/Framework/JSONFile/fox.jpg